BOS-287 The function to be imported from auditor is changed from start to get_coroutines (#80)
Jira Issue

BOS-287

Background
Error occured because of auditor method name is changed from start() to get_coroutines()

Traceback (most recent call last):
  File "run-case.py", line 264, in <module>
    run(options, design)
  File "run-case.py", line 127, in run
    blockchains = run_func(options, design)
  File "run-case.py", line 82, in run_default
    [asyncio.ensure_future(auditor.start()) for auditor in auditors.values()]
  File "run-case.py", line 82, in <listcomp>
    [asyncio.ensure_future(auditor.start()) for auditor in auditors.values()]
AttributeError: 'FaultyNodeAuditor' object has no attribute 'start'

Solution
Change function call for using coroutine

Commits
* The function to be imported from auditor is changed from start to get_coroutines
* extract duplicated code to util.py log_current_state method